### ISSUE TITLE
Sample Programs

### ISSUE THREAD

**Issue by akallem** [Aalk4308/Words#102]
We should make some sample programs (which aren't strictly part of the system tests) that we can use for the presentation and reference in the tutorial.

**Comment by alexthemark** [comment]
Everyone should create a program that is interesting to them. 

Leave a comment of what you are creating so that we don't create the same things.

**Comment by akallem** [comment]
Made simple CountingUp program, counting Fibonacci numbers, Marco Polo, and Turing Machine.

**Comment by zwdnyc** [comment]
Make a moving snake. Data visualization with (2d) histograms

**Comment by akallem** [comment]
Whoa that would be wild!  How will you generate the data though?  Programatically?

**Comment by akallem** [comment]
Wangda and I spoke afterward and agreed data visualization won't really work (without programatically creating a Words program from the data, which isn't in line with the language).  Instead, we came up with a "snake" animation, where each link in the snake moves to follow the one ahead of it.
