### ISSUE TITLE
Can Listener Fire Twice?

### ISSUE THREAD

**Issue by akallem** [Aalk4308/Words#108]
If we have "Whenever a person [p] touches a person [q]", will the listener fire twice (since it is evaluated in both directions)?

**Comment by alexthemark** [comment]
I think this is correct behavior.

**Comment by akallem** [comment]
Ok, I agree that it's the right behavior for classes.  But what about if they're named objects?  Whenever Alice touches Bob.  Seems like that will fire twice but it really should fire only once, right?

**Comment by alexthemark** [comment]
no

**Comment by akallem** [comment]
Haha, cool.

**Comment by akallem** [comment]
For future posterity, Alex was here in the room with me when he succinctly said "no" as a joke.  :-)
