### ISSUE TITLE
Consolidate Prompts on Runtime Error

### ISSUE THREAD

**Issue by akallem** [Aalk4308/Words#95]
After a runtime error, we have to print the prompt again to the user.  We have these print statements scattered throughout our code.  It should be harmonized in some way TBD.

**Comment by zwdnyc** [comment]
There is a comment on Line 72 of Frameloop.java, saying
// Note: this should never actually be caught here; it should be caught earlier at the statement level.

But if I add an assert(false) here, I cannot pass the junit tests. It fails at TestINodeMovesPredicate. Not sure what to do with this.
