### ISSUE TITLE
Refactor certain class/method names

### ISSUE THREAD

**Issue by alexthemark** [Aalk4308/Words#97]
From PR #96, there are a number of classes that we would like to rename. I'll do this right after we merge PRs tomorrow, so that we shouldn't effect many active branches. Comment any classes/methods you think should be refactored.

**Comment by akallem** [comment]
Awesome.  Here are my suggestions for discussion:
- WordsLog -> Log
- WordsUI -> GUI
- WordsAction -> Action
- WordsCustomAction -> CustomAction
- WordsCustomActionDefinition -> [delete]
- WordsEnvironment -> Environment
- WordsMove -> MoveAction
- WordsPosition -> Position
- WordsProperty -> Property
- WordsPropertyAssignment -> PropertyAssignAction
- WordsSay -> SayAction
- WordsWait -> WaitAction
- ASTValue.ValueType -> ASTValue.Type
- WordsProperty.PropertyType -> Property.Type
- All Exceptions -> Remove Words

**Comment by alexthemark** [comment]
Only addition I've got to that is to rename Option to Options.

**Comment by alexthemark** [comment]
Replace individual imports with .*'s

**Comment by alexthemark** [comment]
Certain exceptions are keeping their Words prefix so as to not be ambiguous with Java exceptions.
